version: '3.2'
services:
  mysql:
    container_name: mysql
    image: "mysql"
    env_file:
      - mysql.env
    volumes:
      - todoapp-mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
  todoapp:
    container_name: todoapp
    image: todoapp
    ports:
      - '8086:8086'
    env_file:
      - todoapp.env
    restart: always
    depends_on:
      - mysql

volumes:
  todoapp-mysql-data: