version: '3.2'
services:
  postgres:
    container_name: postgres
    image: "postgres"
    env_file:
      - postgres.env
    volumes:
      - todoapp-postgres-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    restart: always
  todoapp:
    container_name: todoapp
    image: todoapp
    ports:
      - '8086:8086'
    env_file:
      - todoapp.env
    restart: always
    depends_on:
      - postgres

volumes:
  todoapp-postgres-data: