# Generated by Django 3.0.2 on 2020-08-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('INPROGRESS', 'INPROGRESS'), ('COMPLETED', 'COMPLETED'), ('ABANDONED', 'ABANDONED')], default='CREATED', max_length=20),
        ),
    ]
